# Generated by Django 4.0.4 on 2022-05-07 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_alter_academicsession_current'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='others',
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father')], default='father', max_length=10, verbose_name='Relation with Student')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('village', models.CharField(max_length=60)),
                ('traditional_authority', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('address', models.TextField(blank=True, verbose_name='Residential Address')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass')),
            ],
            options={
                'ordering': ['student', 'full_name'],
            },
        ),
    ]
