# Generated by Django 4.0.4 on 2022-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_parent_mobile_number_student_medical_doctor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allergies',
            field=models.CharField(max_length=300),
        ),
    ]
