# Generated by Django 4.0.4 on 2022-05-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
