# Generated by Django 4.0.4 on 2022-05-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_guardian_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='district',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='traditional_authority',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='village',
        ),
    ]
